run:
  timeout: 3m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - revive

issues:
  exclude-rules:
    - linters:
        - revive
      text: "exported:"
